### ISSUE TITLE
TypeError: Cannot access offset of type string on string

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [LotarProject/dokuwiki-plugin-semantic#22]
Hi,

in our wiki I get the following error message:
```
TypeError: Cannot access offset of type string on string
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the semantic plugin.

More info has been written to the DokuWiki error log.

```
The log file gives out the following information:

```
2022-11-04 12:18:44
TypeError: Cannot access offset of type string on string
/var/www/html/wiki/lib/plugins/semantic/helper.php(129)
#0 /var/www/html/wiki/lib/plugins/semantic/helper.php(214): helper_plugin_semantic->getDescription()
#1 /var/www/html/wiki/lib/plugins/semantic/helper.php(302): helper_plugin_semantic->getStructuredData()
#2 /var/www/html/wiki/lib/plugins/semantic/action.php(149): helper_plugin_semantic->getJsonLD()
#3 /var/www/html/wiki/inc/Extension/EventHandler.php(81): action_plugin_semantic->json_ld(Object(dokuwiki\Extension\Event), NULL)
#4 /var/www/html/wiki/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
#5 /var/www/html/wiki/inc/Extension/Event.php(132): dokuwiki\Extension\Event->advise_before(true)
#6 /var/www/html/wiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('_tpl_metaheader...', true)
#7 /var/www/html/wiki/inc/template.php(364): dokuwiki\Extension\Event::createAndTrigger('TPL_METAHEADER_...', Array, '_tpl_metaheader...', true)
#8 /var/www/html/wiki/lib/tpl/bootstrap3/main.php(32): tpl_metaheaders()
#9 /var/www/html/wiki/inc/actions.php(27): include('/var/www/html/w...')
#10 /var/www/html/wiki/doku.php(126): act_dispatch()
#11 {main}
```
Can someone give a hint how to solve this?

Best regards
Juergen

**Comment by giterlizzi** [comment]
FIXED in last release
